.

diff --git a/.github/workflows/Check.yaml b/.github/workflows/Check.yaml
--- a/.github/workflows/Check.yaml
+++ b/.github/workflows/Check.yaml
@@ -1,4 +1,4 @@
----
+
 name: Check
 
 on:
@@ -17,82 +17,82 @@ jobs:
   name: Check Reuse 🔄
   uses: ./.github/workflow/R-CMD-check.yaml
 
-  R-CMD-check:
-    runs-on: ${{ matrix.config.os }}
+  # R-CMD-check:
+  #   runs-on: ${{ matrix.config.os }}
 
-    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
+  #   name: ${{ matrix.config.os }} (${{ matrix.config.r }})
 
-    strategy:
-      fail-fast: false
-      matrix:
-        config:
-          # - {os: macos-latest,   r: 'release'}
-          # - {os: windows-latest, r: 'release'}
-          # - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
-          - {os: ubuntu-latest,   r: 'release'}
-          # - {os: ubuntu-latest,   r: 'oldrel-1'}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       config:
+  #         # - {os: macos-latest,   r: 'release'}
+  #         # - {os: windows-latest, r: 'release'}
+  #         # - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
+  #         - {os: ubuntu-latest,   r: 'release'}
+  #         # - {os: ubuntu-latest,   r: 'oldrel-1'}
 
-    env:
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-      R_KEEP_PKG_SOURCE: yes
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  #     R_KEEP_PKG_SOURCE: yes
 
-    steps:
-      - uses: actions/checkout@v4
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - uses: r-lib/actions/setup-pandoc@v2
+  #     - uses: r-lib/actions/setup-pandoc@v2
 
-      - uses: r-lib/actions/setup-r@v2
-        with:
-          r-version: ${{ matrix.config.r }}
-          http-user-agent: ${{ matrix.config.http-user-agent }}
-          use-public-rspm: true
+  #     - uses: r-lib/actions/setup-r@v2
+  #       with:
+  #         r-version: ${{ matrix.config.r }}
+  #         http-user-agent: ${{ matrix.config.http-user-agent }}
+  #         use-public-rspm: true
 
-      - uses: r-lib/actions/setup-r-dependencies@v2
-        with:
-          extra-packages: any::rcmdcheck
-          needs: check
+  #     - uses: r-lib/actions/setup-r-dependencies@v2
+  #       with:
+  #         extra-packages: any::rcmdcheck
+  #         needs: check
 
-      - uses: r-lib/actions/check-r-package@v2
-        with:
-          upload-snapshots: true
+  #     - uses: r-lib/actions/check-r-package@v2
+  #       with:
+  #         upload-snapshots: true
 
-  test-coverage:
-    runs-on: ubuntu-latest
-    env:
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  # test-coverage:
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
-    steps:
-      - uses: actions/checkout@v4
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - uses: r-lib/actions/setup-r@v2
-        with:
-          use-public-rspm: true
+  #     - uses: r-lib/actions/setup-r@v2
+  #       with:
+  #         use-public-rspm: true
 
-      - uses: r-lib/actions/setup-r-dependencies@v2
-        with:
-          extra-packages: any::covr
-          needs: coverage
+  #     - uses: r-lib/actions/setup-r-dependencies@v2
+  #       with:
+  #         extra-packages: any::covr
+  #         needs: coverage
 
-      - name: Test coverage
-        run: |
-          covr::codecov(
-            quiet = FALSE,
-            clean = FALSE,
-            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
-          )
-        shell: Rscript {0}
+  #     - name: Test coverage
+  #       run: |
+  #         covr::codecov(
+  #           quiet = FALSE,
+  #           clean = FALSE,
+  #           install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
+  #         )
+  #       shell: Rscript {0}
 
-      - name: Show testthat output
-        if: always()
-        run: |
-          ## --------------------------------------------------------------------
-          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+  #     - name: Show testthat output
+  #       if: always()
+  #       run: |
+  #         ## --------------------------------------------------------------------
+  #         find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
+  #       shell: bash
 
-    - name: Upload test results
-      if: failure()
-      uses: actions/upload-artifact@v4
-      with:
-        name: coverage-test-failures
-        path: ${{ runner.temp }}/package
+  #   - name: Upload test results
+  #     if: failure()
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: coverage-test-failures
+  #       path: ${{ runner.temp }}/package
 
